/*
 * This file was automatically generated by EvoSuite
 * Fri May 05 17:34:42 GMT 2023
 */

package com;

import org.junit.Test;
import static org.junit.Assert.*;
import com.JohnnySunApplication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JohnnySunApplication_ESTest extends JohnnySunApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JohnnySunApplication johnnySunApplication0 = new JohnnySunApplication();
  }
}
