/*
 * This file was automatically generated by EvoSuite
 * Fri May 05 16:39:31 GMT 2023
 */

package com.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import com.entity.IdInfoEntity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IdInfoEntity_ESTest extends IdInfoEntity_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IdInfoEntity idInfoEntity0 = new IdInfoEntity();
      idInfoEntity0.setCrdTp("WzVkIc D()2X");
      String string0 = idInfoEntity0.getCrdTp();
      assertEquals("WzVkIc D()2X", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IdInfoEntity idInfoEntity0 = new IdInfoEntity();
      idInfoEntity0.setCrdNo("WzVkIc D()2X");
      String string0 = idInfoEntity0.getCrdNo();
      assertEquals("WzVkIc D()2X", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IdInfoEntity idInfoEntity0 = new IdInfoEntity();
      String string0 = idInfoEntity0.getCrdNo();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IdInfoEntity idInfoEntity0 = new IdInfoEntity();
      idInfoEntity0.setCrdTp("");
      String string0 = idInfoEntity0.getCrdTp();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IdInfoEntity idInfoEntity0 = new IdInfoEntity();
      String string0 = idInfoEntity0.getCrdTp();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      IdInfoEntity idInfoEntity0 = new IdInfoEntity();
      idInfoEntity0.setCrdNo("");
      String string0 = idInfoEntity0.getCrdNo();
      assertEquals("", string0);
  }
}
