/*
 * This file was automatically generated by EvoSuite
 * Fri May 05 17:33:36 GMT 2023
 */

package com.common;

import org.junit.Test;
import static org.junit.Assert.*;
import com.common.NdcException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NdcException_ESTest extends NdcException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NdcException ndcException0 = new NdcException("");
  }
}
